# Generated by Django 2.1.7 on 2019-03-14 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
                ('round', models.CharField(max_length=10)),
                ('white', models.CharField(max_length=100)),
                ('black', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=10)),
                ('annotator', models.CharField(max_length=200)),
                ('plycount', models.CharField(max_length=200)),
                ('time_control', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('termination', models.CharField(max_length=200)),
                ('mode', models.CharField(max_length=200)),
                ('fen', models.CharField(max_length=400)),
                ('move_text', models.TextField()),
                ('comments', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
