# Generated by Django 2.1.7 on 2019-03-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='annotator',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='comments',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='fen',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='plycount',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='termination',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_control',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
